apiVersion: v1
kind: Secret
metadata:
  name: postgre-pets-secret
type: Opaque # 인코드 암호화
data:
  POSTGRES_USER: ZG9ja2VydXNlcg== # dockeruser
  POSTGRES_PASSWORD: YWJjMTIzIQ== # abc123!
  POSTGRES_DB: cGV0cw== # pets