apiVersion: v1
kind: Service
metadata:
  name: argo-njnginx-svc
spec:
  selector:
    app: argo-njnginx
  ports:
    - port: {{.Values.service.nginx.port}}
      protocol: TCP
      targetPort: {{.Values.service.nginx.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-nodejs-svc
spec:
  selector:
    app: argo-nodejs
  ports:
    - port: {{.Values.service.nodejs.port}}
      protocol: TCP
      targetPort: {{.Values.service.nodejs.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: argo-postgre-svc
spec:
  selector:
    app: argo-postgre13
  ports:
    - port: {{.Values.service.postgre.port}}
      protocol: TCP
      targetPort: {{.Values.service.postgre.targetPort}}
